#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_DUSTY_1                      42
#define TRAINER_CHIP                         43
#define TRAINER_FOSTER                       44
#define TRAINER_DUSTY_2                      45
#define TRAINER_DUSTY_3                      46
#define TRAINER_GABBY_AND_TY_1               47
#define TRAINER_GABBY_AND_TY_2               48
#define TRAINER_GABBY_AND_TY_3               49
#define TRAINER_LOLA_1                       50
#define TRAINER_AUSTINA                      51
#define TRAINER_GWEN                         52
#define TRAINER_LOLA_2                       53
#define TRAINER_LOLA_3                       54
#define TRAINER_RICKY_1                      55
#define TRAINER_SIMON                        56
#define TRAINER_CHARLIE                      57
#define TRAINER_RICKY_2                      58
#define TRAINER_RICKY_3                      59
#define TRAINER_RANDALL                      60
#define TRAINER_PARKER                       61
#define TRAINER_GEORGE                       62
#define TRAINER_BERKE                        63
#define TRAINER_BRAXTON                      64
#define TRAINER_VINCENT                      65
#define TRAINER_LEROY                        66
#define TRAINER_WILTON_1                     67
#define TRAINER_EDGAR                        68
#define TRAINER_ALBERT                       69
#define TRAINER_SAMUEL                       70
#define TRAINER_VITO                         71
#define TRAINER_OWEN                         72
#define TRAINER_WILTON_2                     73
#define TRAINER_WILTON_3                     74
#define TRAINER_WARREN                       75
#define TRAINER_MARY                         76
#define TRAINER_ALEXIA                       77
#define TRAINER_JODY                         78
#define TRAINER_WENDY                        79
#define TRAINER_KEIRA                        80
#define TRAINER_BROOKE_1                     81
#define TRAINER_JENNIFER                     82
#define TRAINER_HOPE                         83
#define TRAINER_SHANNON                      84
#define TRAINER_MICHELLE                     85
#define TRAINER_CAROLINE                     86
#define TRAINER_JULIE                       87
#define TRAINER_BROOKE_2                    88
#define TRAINER_BROOKE_3                    89
#define TRAINER_PATRICIA                    90
#define TRAINER_KINDRA                      91
#define TRAINER_TAMMY                       92
#define TRAINER_VALERIE_1                   93
#define TRAINER_TASHA                       94
#define TRAINER_VALERIE_2                   95
#define TRAINER_VALERIE_3                   96
#define TRAINER_CINDY_1                     97
#define TRAINER_DAPHNE                      98
#define TRAINER_GRUNT_SPACE_CENTER_2        99
#define TRAINER_CINDY_2                     100
#define TRAINER_BRIANNA                     101
#define TRAINER_NAOMI                       102
#define TRAINER_CINDY_3                     103
#define TRAINER_MELISSA                     104
#define TRAINER_SHEILA                      105
#define TRAINER_SHIRLEY                     106
#define TRAINER_JESSICA_1                   107
#define TRAINER_CONNIE                      108
#define TRAINER_BRIDGET                     109
#define TRAINER_OLIVIA                      110
#define TRAINER_TIFFANY                     111
#define TRAINER_JESSICA_2                   112
#define TRAINER_JESSICA_3                   113
#define TRAINER_WINSTON_1                   114
#define TRAINER_MOLLIE                      115
#define TRAINER_GARRET                      116
#define TRAINER_WINSTON_2                   117
#define TRAINER_WINSTON_3                   118
#define TRAINER_STEVE_1                     119
#define TRAINER_THALIA_1                    120
#define TRAINER_MARK                        121
#define TRAINER_GRUNT_MT_CHIMNEY_1          122
#define TRAINER_STEVE_2                     123
#define TRAINER_STEVE_3                     124
#define TRAINER_LUIS                        125
#define TRAINER_DOMINIK                     126
#define TRAINER_DOUGLAS                     127
#define TRAINER_DARRIN                      128
#define TRAINER_TONY_1                      129
#define TRAINER_JEROME                      130
#define TRAINER_MATTHEW                     131
#define TRAINER_DAVID                       132
#define TRAINER_SPENCER                     133
#define TRAINER_ROLAND                      134
#define TRAINER_NOLEN                       135
#define TRAINER_STAN                        136
#define TRAINER_BARRY                       137
#define TRAINER_DEAN                        138
#define TRAINER_RODNEY                      139
#define TRAINER_RICHARD                     140
#define TRAINER_HERMAN                      141
#define TRAINER_SANTIAGO                    142
#define TRAINER_GILBERT                     143
#define TRAINER_FRANKLIN                    144
#define TRAINER_KEVIN                       145
#define TRAINER_JACK                        146
#define TRAINER_DUDLEY                      147
#define TRAINER_CHAD                        148
#define TRAINER_TONY_2                      149
#define TRAINER_TONY_3                      150
#define TRAINER_TAKAO                       151
#define TRAINER_HITOSHI                     152
#define TRAINER_KIYO                        153
#define TRAINER_KOICHI                      154
#define TRAINER_NOB_1                       155
#define TRAINER_NOB_2                       156
#define TRAINER_NOB_3                       157
#define TRAINER_YUJI                        158
#define TRAINER_DAISUKE                     159
#define TRAINER_ATSUSHI                     160
#define TRAINER_KIRK                        161
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        162
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        163
#define TRAINER_SHAWN                       164
#define TRAINER_FERNANDO_1                  165
#define TRAINER_DALTON_1                    166
#define TRAINER_DALTON_2                    167
#define TRAINER_DALTON_3                    168
#define TRAINER_COLE                        169
#define TRAINER_JEFF                        170
#define TRAINER_AXLE                        171
#define TRAINER_JACE                        172
#define TRAINER_KEEGAN                      173
#define TRAINER_BERNIE_1                    174
#define TRAINER_BERNIE_2                    175
#define TRAINER_BERNIE_3                    176
#define TRAINER_DREW                        177
#define TRAINER_BEAU                        178
#define TRAINER_LARRY                       179
#define TRAINER_SHANE                       180
#define TRAINER_JUSTIN                      181
#define TRAINER_ETHAN_1                     182
#define TRAINER_AUTUMN                      183
#define TRAINER_TRAVIS                      184
#define TRAINER_ETHAN_2                     185
#define TRAINER_ETHAN_3                     186
#define TRAINER_BRENT                       187
#define TRAINER_DONALD                      188
#define TRAINER_TAYLOR                      189
#define TRAINER_JEFFREY_1                   190
#define TRAINER_DEREK                       191
#define TRAINER_JEFFREY_2                   192
#define TRAINER_JEFFREY_3                   193
#define TRAINER_EDWARD                      194
#define TRAINER_PRESTON                     195
#define TRAINER_VIRGIL                      196
#define TRAINER_BLAKE                       197
#define TRAINER_WILLIAM                     198
#define TRAINER_JOSHUA                      199
#define TRAINER_CAMERON_1                   200
#define TRAINER_CAMERON_2                   201
#define TRAINER_CAMERON_3                   202
#define TRAINER_JACLYN                      203
#define TRAINER_HANNAH                      204
#define TRAINER_SAMANTHA                    205
#define TRAINER_MAURA                       206
#define TRAINER_KAYLA                       207
#define TRAINER_ALEXIS                      208
#define TRAINER_JACKI_1                     209
#define TRAINER_JACKI_2                     210
#define TRAINER_JACKI_3                     211
#define TRAINER_WALTER_1                    212
#define TRAINER_MICAH                       213
#define TRAINER_THOMAS                      214
#define TRAINER_WALTER_2                    215
#define TRAINER_WALTER_3                    216
#define TRAINER_SIDNEY                      217
#define TRAINER_PHOEBE                      218
#define TRAINER_GLACIA                      219
#define TRAINER_DRAKE                       220
#define TRAINER_ROXANNE_1                   221
#define TRAINER_BRAWLY_1                    222
#define TRAINER_WATTSON_1                   223
#define TRAINER_FLANNERY_1                  224
#define TRAINER_NORMAN_1                    225
#define TRAINER_WINONA_1                    226
#define TRAINER_TATE_AND_LIZA_1             227
#define TRAINER_JUAN_1                      228
#define TRAINER_JERRY_1                     229
#define TRAINER_TED                         230
#define TRAINER_PAUL                        231
#define TRAINER_JERRY_2                     232
#define TRAINER_JERRY_3                     233
#define TRAINER_KAREN_1                     234
#define TRAINER_GEORGIA                     235
#define TRAINER_KAREN_2                     236
#define TRAINER_KAREN_3                     237
#define TRAINER_KATE_AND_JOY                238
#define TRAINER_ANNA_AND_MEG_1              239
#define TRAINER_ANNA_AND_MEG_2              240
#define TRAINER_ANNA_AND_MEG_3              241
#define TRAINER_VICTOR                      242
#define TRAINER_MIGUEL_1                    243
#define TRAINER_COLTON                      244
#define TRAINER_MIGUEL_2                    245
#define TRAINER_MIGUEL_3                    246
#define TRAINER_VICTORIA                    247
#define TRAINER_VANESSA                     248
#define TRAINER_BETHANY                     249
#define TRAINER_ISABEL_1                    250
#define TRAINER_ISABEL_2                    251
#define TRAINER_ISABEL_3                    252
#define TRAINER_TIMOTHY_1                   253
#define TRAINER_TIMOTHY_2                   254
#define TRAINER_TIMOTHY_3                   255
#define TRAINER_VICKY                       256
#define TRAINER_SHELBY_1                    257
#define TRAINER_SHELBY_2                    258
#define TRAINER_SHELBY_3                    259
#define TRAINER_CALVIN_1                    260
#define TRAINER_BILLY                       261
#define TRAINER_JOSH                        262
#define TRAINER_TOMMY                       263
#define TRAINER_JOEY                        264
#define TRAINER_BEN                         265
#define TRAINER_QUINCY                      266
#define TRAINER_KATELYNN                    267
#define TRAINER_JAYLEN                      268
#define TRAINER_DILLON                      269
#define TRAINER_CALVIN_2                    270
#define TRAINER_CALVIN_3                    271
#define TRAINER_EDDIE                       272
#define TRAINER_ALLEN                       273
#define TRAINER_TIMMY                       274
#define TRAINER_WALLACE                     275
#define TRAINER_ANDREW                      276
#define TRAINER_IVAN                        277
#define TRAINER_CLAUDE                      278
#define TRAINER_ELLIOT_1                    279
#define TRAINER_NED                         280
#define TRAINER_DALE                        281
#define TRAINER_NOLAN                       282
#define TRAINER_BARNY                       283
#define TRAINER_WADE                        284
#define TRAINER_CARTER                      285
#define TRAINER_ELLIOT_2                    286
#define TRAINER_ELLIOT_3                    287
#define TRAINER_RONALD                      288
#define TRAINER_JACOB                       289
#define TRAINER_ANTHONY                     290
#define TRAINER_BENJAMIN_1                  291
#define TRAINER_BENJAMIN_2                  292
#define TRAINER_BENJAMIN_3                  293
#define TRAINER_ABIGAIL_1                   294
#define TRAINER_JASMINE                     295
#define TRAINER_ABIGAIL_2                   296
#define TRAINER_ABIGAIL_3                   297
#define TRAINER_DYLAN_1                     298
#define TRAINER_DYLAN_2                     299
#define TRAINER_DYLAN_3                     300
#define TRAINER_MARIA_1                     301
#define TRAINER_MARIA_2                     302
#define TRAINER_MARIA_3                     303
#define TRAINER_CAMDEN                      304
#define TRAINER_DEMETRIUS                   305
#define TRAINER_ISAIAH_1                    306
#define TRAINER_PABLO_1                     307
#define TRAINER_CHASE                       308
#define TRAINER_ISAIAH_2                    309
#define TRAINER_ISAIAH_3                    310
#define TRAINER_ISOBEL                      311
#define TRAINER_DONNY                       312
#define TRAINER_TALIA                       313
#define TRAINER_KATELYN_1                   314
#define TRAINER_ALLISON                     315
#define TRAINER_KATELYN_2                   316
#define TRAINER_KATELYN_3                   317
#define TRAINER_NICOLAS_1                   318
#define TRAINER_NICOLAS_2                   319
#define TRAINER_NICOLAS_3                   320
#define TRAINER_AARON                       321
#define TRAINER_PERRY                       322
#define TRAINER_HUGH                        323
#define TRAINER_PHIL                        324
#define TRAINER_JARED                       325
#define TRAINER_HUMBERTO                    326
#define TRAINER_PRESLEY                     327
#define TRAINER_EDWARDO                     328
#define TRAINER_COLIN                       329
#define TRAINER_ROBERT_1                    330
#define TRAINER_BENNY                       331
#define TRAINER_CHESTER                     332
#define TRAINER_ROBERT_2                    333
#define TRAINER_ROBERT_3                    334
#define TRAINER_ALEX                        335
#define TRAINER_BECK                        336
#define TRAINER_YASU                        337
#define TRAINER_TAKASHI                     338
#define TRAINER_DIANNE                      339
#define TRAINER_JANI                        340
#define TRAINER_LAO_1                       341
#define TRAINER_LUNG                        342
#define TRAINER_LAO_2                       343
#define TRAINER_LAO_3                       344
#define TRAINER_JOCELYN                     345
#define TRAINER_LAURA                       346
#define TRAINER_CYNDY_1                     347
#define TRAINER_CORA                        348
#define TRAINER_PAULA                       349
#define TRAINER_CYNDY_2                     350
#define TRAINER_CYNDY_3                     351
#define TRAINER_MADELINE_1                  352
#define TRAINER_CLARISSA                    353
#define TRAINER_ANGELICA                    354
#define TRAINER_MADELINE_2                  355
#define TRAINER_MADELINE_3                  356
#define TRAINER_BEVERLY                     357
#define TRAINER_IMANI                       358
#define TRAINER_KYLA                        359
#define TRAINER_DENISE                      360
#define TRAINER_BETH                        361
#define TRAINER_TARA                        362
#define TRAINER_MISSY                       363
#define TRAINER_ALICE                       364
#define TRAINER_JENNY_1                     365
#define TRAINER_GRACE                       366
#define TRAINER_TANYA                       367
#define TRAINER_SHARON                      368
#define TRAINER_NIKKI                       369
#define TRAINER_BRENDA                      370
#define TRAINER_KATIE                       371
#define TRAINER_SUSIE                       372
#define TRAINER_KARA                        373
#define TRAINER_DANA                        374
#define TRAINER_SIENNA                      375
#define TRAINER_DEBRA                       376
#define TRAINER_LINDA                       377
#define TRAINER_KAYLEE                      378
#define TRAINER_LAUREL                      379
#define TRAINER_CARLEE                      380
#define TRAINER_JENNY_2                     381
#define TRAINER_JENNY_3                     382
#define TRAINER_HEIDI                       383
#define TRAINER_BECKY                       384
#define TRAINER_CAROL                       385
#define TRAINER_NANCY                       386
#define TRAINER_MARTHA                      387
#define TRAINER_DIANA_1                     388
#define TRAINER_CEDRIC                      389
#define TRAINER_IRENE                       390
#define TRAINER_DIANA_2                     391
#define TRAINER_DIANA_3                     392
#define TRAINER_AMY_AND_LIV_1               393
#define TRAINER_AMY_AND_LIV_2               394
#define TRAINER_GINA_AND_MIA_1              395
#define TRAINER_MIU_AND_YUKI                396
#define TRAINER_AMY_AND_LIV_3               397
#define TRAINER_GINA_AND_MIA_2              398
#define TRAINER_HUEY                        399
#define TRAINER_EDMOND                      400
#define TRAINER_ERNEST_1                    401
#define TRAINER_DWAYNE                      402
#define TRAINER_PHILLIP                     403
#define TRAINER_LEONARD                     404
#define TRAINER_DUNCAN                      405
#define TRAINER_ERNEST_2                    406
#define TRAINER_ERNEST_3                    407
#define TRAINER_ELI                         408
#define TRAINER_ANNIKA                      409
#define TRAINER_JAZMYN                      410
#define TRAINER_JONAS                       411
#define TRAINER_KAYLEY                      412
#define TRAINER_AURON                       413
#define TRAINER_KELVIN                      414
#define TRAINER_MARLEY                      415
#define TRAINER_REYNA                       416
#define TRAINER_HUDSON                      417
#define TRAINER_CONOR                       418
#define TRAINER_EDWIN_1                     419
#define TRAINER_HECTOR                      420
#define TRAINER_TABITHA_MOSSDEEP            421
#define TRAINER_EDWIN_2                     422
#define TRAINER_EDWIN_3                     423
#define TRAINER_WALLY_VR_1                  424
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    425
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    426
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    427
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   428
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   429
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   430
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   431
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   432
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   433
#define TRAINER_MAY_ROUTE_103_MUDKIP        434
#define TRAINER_MAY_ROUTE_110_MUDKIP        435
#define TRAINER_MAY_ROUTE_119_MUDKIP        436
#define TRAINER_MAY_ROUTE_103_TREECKO       437
#define TRAINER_MAY_ROUTE_110_TREECKO       438
#define TRAINER_MAY_ROUTE_119_TREECKO       439
#define TRAINER_MAY_ROUTE_103_TORCHIC       440
#define TRAINER_MAY_ROUTE_110_TORCHIC       441
#define TRAINER_MAY_ROUTE_119_TORCHIC       442
#define TRAINER_ISAAC_1                     443
#define TRAINER_DAVIS                       444
#define TRAINER_MITCHELL                    445
#define TRAINER_ISAAC_2                     446
#define TRAINER_ISAAC_3                     447
#define TRAINER_LYDIA_1                     448
#define TRAINER_HALLE                       449
#define TRAINER_GARRISON                    450
#define TRAINER_LYDIA_2                     451
#define TRAINER_LYDIA_3                     452
#define TRAINER_JACKSON_1                   453
#define TRAINER_LORENZO                     454
#define TRAINER_SEBASTIAN                   455
#define TRAINER_JACKSON_2                   456
#define TRAINER_JACKSON_3                   457
#define TRAINER_CATHERINE_1                 458
#define TRAINER_JENNA                       459
#define TRAINER_SOPHIA                      460
#define TRAINER_CATHERINE_2                 461
#define TRAINER_CATHERINE_3                 462
#define TRAINER_JULIO                       463
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     464
#define TRAINER_GRUNT_UNUSED                465
#define TRAINER_GRUNT_MT_PYRE_4             466
#define TRAINER_GRUNT_JAGGED_PASS           467
#define TRAINER_MARC                        468
#define TRAINER_BRENDEN                     469
#define TRAINER_LILITH                      470
#define TRAINER_CRISTIAN                    471
#define TRAINER_SYLVIA                      472
#define TRAINER_LEONARDO                    473
#define TRAINER_ATHENA                      474
#define TRAINER_HARRISON                    475
#define TRAINER_GRUNT_MT_CHIMNEY_2          476
#define TRAINER_CLARENCE                    477
#define TRAINER_TERRY                       478
#define TRAINER_NATE                        479
#define TRAINER_KATHLEEN                    480
#define TRAINER_CLIFFORD                    481
#define TRAINER_NICHOLAS                    482
#define TRAINER_GRUNT_SPACE_CENTER_3        483
#define TRAINER_GRUNT_SPACE_CENTER_4        484
#define TRAINER_GRUNT_SPACE_CENTER_5        485
#define TRAINER_GRUNT_SPACE_CENTER_6        486
#define TRAINER_GRUNT_SPACE_CENTER_7        487
#define TRAINER_MACEY                       488
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    489
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     490
#define TRAINER_PAXTON                      491
#define TRAINER_ISABELLA                    492
#define TRAINER_GRUNT_WEATHER_INST_5        493
#define TRAINER_TABITHA_MT_CHIMNEY          494
#define TRAINER_JONATHAN                    495
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    496
#define TRAINER_MAY_RUSTBORO_MUDKIP         497
#define TRAINER_MAXIE_MAGMA_HIDEOUT         498
#define TRAINER_MAXIE_MT_CHIMNEY            499
#define TRAINER_TIANA                       500
#define TRAINER_HALEY_1                     501
#define TRAINER_JANICE                      502
#define TRAINER_VIVI                        503
#define TRAINER_HALEY_2                     504
#define TRAINER_HALEY_3                     505
#define TRAINER_SALLY                       506
#define TRAINER_ROBIN                       507
#define TRAINER_ANDREA                      508
#define TRAINER_CRISSY                      509
#define TRAINER_RICK                        510
#define TRAINER_LYLE                        511
#define TRAINER_JOSE                        512
#define TRAINER_DOUG                        513
#define TRAINER_GREG                        514
#define TRAINER_KENT                        515
#define TRAINER_JAMES_1                     516
#define TRAINER_JAMES_2                     517
#define TRAINER_JAMES_3                     518
#define TRAINER_BRICE                       519
#define TRAINER_TRENT_1                     520
#define TRAINER_LENNY                       521
#define TRAINER_LUCAS_1                     522
#define TRAINER_ALAN                        523
#define TRAINER_CLARK                       524
#define TRAINER_ERIC                        525
#define TRAINER_LUCAS_2                     526
#define TRAINER_MIKE_1                      527
#define TRAINER_MIKE_2                      528
#define TRAINER_TRENT_2                     529
#define TRAINER_TRENT_3                     530
#define TRAINER_DEZ_AND_LUKE                531
#define TRAINER_LEA_AND_JED                 532
#define TRAINER_KIRA_AND_DAN_1              533
#define TRAINER_KIRA_AND_DAN_2              534
#define TRAINER_KIRA_AND_DAN_3              535
#define TRAINER_JOHANNA                     536
#define TRAINER_GERALD                      537
#define TRAINER_VIVIAN                      538
#define TRAINER_DANIELLE                    539
#define TRAINER_HIDEO                       540
#define TRAINER_KEIGO                       541
#define TRAINER_RILEY                       542
#define TRAINER_FLINT                       543
#define TRAINER_ASHLEY                      544
#define TRAINER_WALLY_MAUVILLE              545
#define TRAINER_WALLY_VR_2                  546
#define TRAINER_WALLY_VR_3                  547
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     548
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    549
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    550
#define TRAINER_MAY_LILYCOVE_MUDKIP         551
#define TRAINER_MAY_LILYCOVE_TREECKO        552
#define TRAINER_MAY_LILYCOVE_TORCHIC        553
#define TRAINER_JONAH                       554
#define TRAINER_HENRY                       555
#define TRAINER_ROGER                       556
#define TRAINER_ALEXA                       557
#define TRAINER_RUBEN                       558
#define TRAINER_KOJI_1                      559
#define TRAINER_WAYNE                       560
#define TRAINER_AIDAN                       561
#define TRAINER_REED                        562
#define TRAINER_TISHA                       563
#define TRAINER_TORI_AND_TIA                564
#define TRAINER_KIM_AND_IRIS                565
#define TRAINER_TYRA_AND_IVY                566
#define TRAINER_MEL_AND_PAUL                567
#define TRAINER_JOHN_AND_JAY_1              568
#define TRAINER_JOHN_AND_JAY_2              569
#define TRAINER_JOHN_AND_JAY_3              570
#define TRAINER_RELI_AND_IAN                571
#define TRAINER_LILA_AND_ROY_1              572
#define TRAINER_LILA_AND_ROY_2              573
#define TRAINER_LILA_AND_ROY_3              574
#define TRAINER_LISA_AND_RAY                575
#define TRAINER_CHRIS                       576
#define TRAINER_DAWSON                      577
#define TRAINER_SARAH                       578
#define TRAINER_DARIAN                      579
#define TRAINER_HAILEY                      580
#define TRAINER_CHANDLER                    581
#define TRAINER_KALEB                       582
#define TRAINER_JOSEPH                      583
#define TRAINER_ALYSSA                      584
#define TRAINER_MARCOS                      585
#define TRAINER_RHETT                       586
#define TRAINER_TYRON                       587
#define TRAINER_CELINA                      588
#define TRAINER_BIANCA                      589
#define TRAINER_HAYDEN                      590
#define TRAINER_SOPHIE                      591
#define TRAINER_COBY                        592
#define TRAINER_LAWRENCE                    593
#define TRAINER_WYATT                       594
#define TRAINER_ANGELINA                    595
#define TRAINER_KAI                         596
#define TRAINER_CHARLOTTE                   597
#define TRAINER_DEANDRE                     598
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       599
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       600
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       601
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       602
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       603
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       604
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       605
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       606
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       607
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      608
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      609
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      610
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      611
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      612
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      613
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      614
#define TRAINER_TABITHA_MAGMA_HIDEOUT       615
#define TRAINER_DARCY                       616
#define TRAINER_MAXIE_MOSSDEEP              617
#define TRAINER_PETE                        618
#define TRAINER_ISABELLE                    619
#define TRAINER_ANDRES_1                    620
#define TRAINER_JOSUE                       621
#define TRAINER_CAMRON                      622
#define TRAINER_CORY_1                      623
#define TRAINER_CAROLINA                    624
#define TRAINER_ELIJAH                      625
#define TRAINER_CELIA                       626
#define TRAINER_BRYAN                       627
#define TRAINER_BRANDEN                     628
#define TRAINER_BRYANT                      629
#define TRAINER_SHAYLA                      630
#define TRAINER_KYRA                        631
#define TRAINER_JAIDEN                      632
#define TRAINER_ALIX                        633
#define TRAINER_HELENE                      634
#define TRAINER_MARLENE                     635
#define TRAINER_DEVAN                       636
#define TRAINER_JOHNSON                     637
#define TRAINER_MELINA                      638
#define TRAINER_BRANDI                      639
#define TRAINER_AISHA                       640
#define TRAINER_MAKAYLA                     641
#define TRAINER_FABIAN                      642
#define TRAINER_DAYTON                      643
#define TRAINER_RACHEL                      644
#define TRAINER_LEONEL                      645
#define TRAINER_CALLIE                      646
#define TRAINER_CALE                        647
#define TRAINER_MYLES                       648
#define TRAINER_PAT                         649
#define TRAINER_CRISTIN_1                   650
#define TRAINER_MAY_RUSTBORO_TREECKO        651
#define TRAINER_MAY_RUSTBORO_TORCHIC        652
#define TRAINER_ROXANNE_2                   653
#define TRAINER_ROXANNE_3                   654
#define TRAINER_BRAWLY_2                    655
#define TRAINER_BRAWLY_3                    656
#define TRAINER_BRAWLY_4                    657
#define TRAINER_BRAWLY_5                    658
#define TRAINER_WATTSON_2                   659
#define TRAINER_WATTSON_3                   660
#define TRAINER_WATTSON_4                   661
#define TRAINER_WATTSON_5                   662
#define TRAINER_FLANNERY_2                  663
#define TRAINER_FLANNERY_3                  664
#define TRAINER_NORMAN_2                    665
#define TRAINER_NORMAN_3                    666
#define TRAINER_WINONA_2                    667
#define TRAINER_WINONA_3                    668
#define TRAINER_WINONA_4                    669
#define TRAINER_STEVEN_GRANITE_CAVE         670
#define TRAINER_TATE_AND_LIZA_2             671
#define TRAINER_TATE_AND_LIZA_3             672
#define TRAINER_JUAN_2                      673
#define TRAINER_JUAN_3                      674
#define TRAINER_JUAN_4                      675
#define TRAINER_JUAN_5                      676
#define TRAINER_ANGELO                      677
#define TRAINER_DARIUS                      678
#define TRAINER_STEVEN                      679
#define TRAINER_ANABEL                      680
#define TRAINER_TUCKER                      681
#define TRAINER_SPENSER                     682
#define TRAINER_GRETA                       683
#define TRAINER_NOLAND                      684
#define TRAINER_LUCY                        685
#define TRAINER_BRANDON                     686
#define TRAINER_ANDRES_2                    687
#define TRAINER_ANDRES_3                    688
#define TRAINER_CORY_2                      689
#define TRAINER_CORY_3                      690
#define TRAINER_PABLO_2                     691
#define TRAINER_PABLO_3                     692
#define TRAINER_KOJI_2                      693
#define TRAINER_KOJI_3                      694
#define TRAINER_CRISTIN_2                   695
#define TRAINER_CRISTIN_3                   696
#define TRAINER_FERNANDO_2                  697
#define TRAINER_FERNANDO_3                  698
#define TRAINER_SAWYER_2                    699
#define TRAINER_SAWYER_3                    700
#define TRAINER_GABRIELLE_2                 701
#define TRAINER_GABRIELLE_3                 702
#define TRAINER_THALIA_2                    703
#define TRAINER_THALIA_3                    704
#define TRAINER_MARIELA                     705
#define TRAINER_ALVARO                      706
#define TRAINER_EVERETT                     707
#define TRAINER_RED                         708
#define TRAINER_LEAF                        709
#define TRAINER_BRENDAN_PLACEHOLDER         710
#define TRAINER_MAY_PLACEHOLDER             711
#define TRAINER_RITCHER                     712
#define TRAINER_BRAM                        713
#define TRAINER_WALLY_VR_4                  714
#define TRAINER_ARCHIE_MUSEUM                 715
#define TRAINER_TABITHA_DESERT_RUINS             716
#define TRAINER_COURTNEY_DESERT_RUINS            717


// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      718
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
